const { PrismaClient } = require('@prisma/client');
const fs = require('fs');
const path = require('path');

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting Database Seeding...');

  // 1. Read the JSON file
  const dbPath = path.join(__dirname, 'data', 'role_skills_db.json');
  if (!fs.existsSync(dbPath)) {
    console.error(`❌ DB file not found at ${dbPath}`);
    process.exit(1);
  }

  const rawData = fs.readFileSync(dbPath, 'utf8');
  let rolesData;
  try {
    rolesData = JSON.parse(rawData);
  } catch (parseError) {
    console.error('❌ Failed to parse JSON:', parseError);
    process.exit(1);
  }

  // Iterate over each role in the JSON
  for (const [roleTitle, roleDetails] of Object.entries(rolesData)) {
    console.log(`Processing Role: ${roleTitle}`);
    
    // We expect tech_skills inside each role for SMAART logic
    if (!roleDetails.tech_skills) {
      console.warn(`⚠️ Skipping ${roleTitle} - no tech_skills found.`);
      continue;
    }

    // 2. Upsert the Role into PostgreSQL
    // We set a default requiredMatchScore of 0.6 if undefined
    const roleRecord = await prisma.role.upsert({
      where: { title: roleTitle },
      update: {},
      create: {
        title: roleTitle,
        description: `Autogenerated description for ${roleTitle}`,
        requiredMatchScore: 0.6 
      }
    });

    // 3. Process each skill in this role
    for (const skillObj of roleDetails.tech_skills) {
      if (!skillObj.skill_name) continue;

      const skillName = skillObj.skill_name;
      // CRITICAL, HIGH, MEDIUM, LOW mapped to priority
      const priority = skillObj.priority || 'MEDIUM';
      
      let weight = 1.0;
      if (priority === 'CRITICAL') weight = 2.0;
      if (priority === 'HIGH') weight = 1.5;
      if (priority === 'MEDIUM') weight = 1.0;
      if (priority === 'LOW') weight = 0.5;

      // Uniqueness Score arbitrary mapping based on priority for now
      let uniquenessScore = weight * 0.8;

      // 4. Upsert the Skill
      const skillRecord = await prisma.skill.upsert({
        where: { name: skillName },
        update: {},
        create: {
          name: skillName,
          category: 'technical',
          uniquenessScore: uniquenessScore
        }
      });

      // 5. Connect Role to Skill via RoleSkill
      await prisma.roleSkill.upsert({
        where: {
          roleId_skillId: {
            roleId: roleRecord.id,
            skillId: skillRecord.id
          }
        },
        update: {
          priority: priority,
          weight: weight
        },
        create: {
          roleId: roleRecord.id,
          skillId: skillRecord.id,
          priority: priority,
          weight: weight
        }
      });
    }
  }

  console.log('✅ Database Seeding Completed Successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
